# .github/workflows/autograding.yml

name: Autograding

on:
  push:
    paths:
      - 'Ex1/**'
      - 'Ex2/**'
      - 'Ex3/**'
      - 'tests/**'
      - 'package.json'
      - 'jest.config.js'
      - 'tsconfig.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instal·lar dependències
        run: npm install

      - name: Compilar TypeScript
        run: npx tsc --noEmit

      - name: Executar testos amb Jest
        run: npm test
